// Package generator produces random txid hashes and submits them to the Merkle
// Service at a controlled rate over the configured test duration.
package generator

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/bsv-blockchain/stumpt/internal/config"
	"github.com/bsv-blockchain/stumpt/internal/metrics"
)

// Generator drives the txid submission pipeline.
type Generator struct {
	cfg    *config.Config
	mc     *metrics.Collector
	doneCh chan struct{}
}

// New creates a Generator.
func New(cfg *config.Config, mc *metrics.Collector) *Generator {
	return &Generator{
		cfg:    cfg,
		mc:     mc,
		doneCh: make(chan struct{}),
	}
}

// Done returns a channel that is closed when all txids have been submitted.
func (g *Generator) Done() <-chan struct{} { return g.doneCh }

// Run generates and submits all txids, blocking until done or ctx is cancelled.
//
// Submission rate = HashesPerBlock / TestDuration.Seconds()
// (≈ 102.4 txids/sec for the defaults, spread over 10 minutes).
//
// Each txid is submitted with a randomly chosen token from [token-0 … token-99],
// simulating 100 distinct submitting businesses.
func (g *Generator) Run(ctx context.Context) {
	defer close(g.doneCh)

	cfg := g.cfg
	client := &http.Client{Timeout: 5 * time.Second}
	interval := cfg.SubmissionInterval()
	target := fmt.Sprintf("http://localhost%s/watch", cfg.MerkleServiceAddr)

	slog.Info("generator starting",
		"hashes", cfg.HashesPerBlock,
		"interval", interval,
		"ratePerSec", fmt.Sprintf("%.1f", 1/interval.Seconds()),
		"duration", cfg.TestDuration,
	)

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for i := 0; i < cfg.HashesPerBlock; i++ {
		select {
		case <-ctx.Done():
			slog.Info("generator cancelled", "submitted", i)
			return
		case <-ticker.C:
		}

		txid := randomHash()
		token := fmt.Sprintf("token-%d", i%cfg.NumBusinesses)

		if err := submitWatch(ctx, client, target, txid, token, cfg.CallbackURL()); err != nil {
			slog.Warn("submit failed", "i", i, "err", err)
			continue
		}

		g.mc.RecordSubmit()

		if (i+1)%10_000 == 0 {
			slog.Info("generator progress",
				"submitted", i+1,
				"remaining", cfg.HashesPerBlock-(i+1),
			)
		}
	}

	slog.Info("generator finished", "total", cfg.HashesPerBlock)
}

// submitWatch POSTs a single /watch registration.
func submitWatch(ctx context.Context, client *http.Client, url, txid, token, cbURL string) error {
	body, err := json.Marshal(map[string]any{
		"txid": txid,
		"callback": map[string]string{
			"url":   cbURL,
			"token": token,
		},
	})
	if err != nil {
		return err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	_ = resp.Body.Close()

	if resp.StatusCode != http.StatusAccepted && resp.StatusCode != http.StatusOK {
		return fmt.Errorf("unexpected status %d", resp.StatusCode)
	}
	return nil
}

// randomHash returns a random 32-byte hash encoded as lowercase hex.
// The bytes are generated by crypto/rand for uniform distribution.
func randomHash() string {
	var b [32]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic("crypto/rand read: " + err.Error())
	}
	return hex.EncodeToString(b[:])
}
